export const COLS_RESIZE = 'COLS_RESIZE'
export const ROWS_RESIZE = 'ROWS_RESIZE'
export const CHANGE_TEXT = 'CHANGE_TEXT'

export const APPLY_STYLE = 'APPLY_STYLE'
export const CHANGE_STYLES = 'CURENT_STYLE'
export const CHANGE_TABLE_NAME = 'CHANGE_TABLE_NAME'

